name: PR Issue Auto-Assignment

on:
  pull_request_target:
    types: [opened, reopened, closed]

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  auto-assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout openwisp-utils
        uses: actions/checkout@v6
        with:
          repository: Eeshu-Yadav/openwisp-utils
          ref: issues/571-automate-assigning-unassigning-issues

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run issue assignment bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: >
          python .github/actions/bot-autoassign/__main__.py
          issue_assignment "$GITHUB_EVENT_PATH"
