name: Issue Assignment Bot

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write

jobs:
  respond-to-assign-request:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run issue assignment bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: >
          python .github/actions/bot-autoassign/__main__.py
          issue_assignment "$GITHUB_EVENT_PATH"
